# Generated by Django 3.1.2 on 2020-10-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkorder',
            old_name='user_profile',
            new_name='user_profiles',
        ),
    ]
