# Generated by Django 3.1.2 on 2020-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='original_shopping_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='drinkorder',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
