# Generated by Django 3.1.2 on 2020-10-21 22:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201021_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
