# Generated by Django 3.1.2 on 2020-10-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201025_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkorderlineitem',
            old_name='drink_name',
            new_name='drink',
        ),
    ]
