# Generated by Django 3.1.2 on 2020-10-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('payment', '0003_auto_20201021_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_orders', to='user_profiles.userprofile'),
        ),
    ]
