# Generated by Django 3.1.2 on 2020-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20201025_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
