# Generated by Django 3.1.2 on 2020-10-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20201022_1057'),
        ('payment', '0004_drinkorder_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drink_orders', to='user_profiles.userprofiles'),
        ),
    ]
