# Generated by Django 3.1.2 on 2020-11-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20201103_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
