# Generated by Django 3.1.2 on 2020-11-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='image_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
