# Generated by Django 3.1.2 on 2020-10-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Drink',
        ),
    ]
