# Generated by Django 3.1.2 on 2020-10-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20201006_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='ml',
            new_name='millilitres',
        ),
    ]
