# Generated by Django 3.1.2 on 2020-10-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20201006_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='url',
        ),
    ]
