# Generated by Django 3.1.2 on 2020-10-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_auto_20201006_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Drink_type',
        ),
    ]
