# Generated by Django 3.1.2 on 2020-10-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkOrders',
            new_name='DrinkOrder',
        ),
    ]
