# Generated by Django 3.1.2 on 2020-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201016_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
