# Generated by Django 3.1.2 on 2020-10-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_drinkorder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
