# Generated by Django 3.1.2 on 2020-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201016_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='order_number',
            field=models.CharField(max_length=32),
        ),
    ]
