# Generated by Django 3.1.2 on 2020-10-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201007_1256'),
        ('checkout', '0008_auto_20201016_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkOrder',
            new_name='DrinkOrder1',
        ),
        migrations.RenameModel(
            old_name='DrinkOrderLineItem',
            new_name='DrinkOrderLineItem1',
        ),
    ]
