# Generated by Django 3.1.2 on 2020-10-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_topic',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('programmatic_name', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(
                    blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drink_type',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drink_type',
            name='programmatic_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('about_us_topic', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='home.about_us_topic')),
            ],
        ),
    ]
