# Generated by Django 3.1.2 on 2020-10-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201007_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us',
            new_name='About_us_para',
        ),
    ]
