# Generated by Django 3.1.2 on 2020-10-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201007_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us_para',
            name='about_us_topic',
        ),
    ]
