# Generated by Django 3.1.2 on 2020-10-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_about_us_para_about_us_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us_para',
        ),
        migrations.DeleteModel(
            name='About_us_topic',
        ),
    ]
