# Generated by Django 3.1.2 on 2020-10-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201029_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
