# Generated by Django 3.1.2 on 2020-10-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201029_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='image_alt',
            new_name='image_description',
        ),
    ]
