# Generated by Django 3.1.2 on 2020-10-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201030_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us_part',
            new_name='About_us_section',
        ),
    ]
