# Generated by Django 3.1.2 on 2020-10-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201030_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='section',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                to='home.about_us_section'),
        ),
    ]
