# Generated by Django 3.1.2 on 2020-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201030_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
