# Generated by Django 3.1.2 on 2020-11-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20201030_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us',
        ),
        migrations.DeleteModel(
            name='About_us_section',
        ),
    ]
