# Generated by Django 3.1.2 on 2020-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofiles_default_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
