# Generated by Django 3.1.2 on 2020-11-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_userprofiles_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='email',
            new_name='default_email',
        ),
    ]
