# Generated by Django 3.1.2 on 2020-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20201113_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='default_email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
