# Generated by Django 3.1.2 on 2020-11-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_remove_userprofiles_default_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='default_full_name',
        ),
    ]
